Feature('fortesza');

Scenario('Register new user', async ({ I }) => {
  I.amOnPage('/register');
  I.fillField('#txt-firstname', 'Stephanie');
  I.wait(2);
  I.fillField('#txt-secondname', 'Danniela');
  I.wait(2);
  I.fillField('#txt-firstsurname', 'Soteldo');
  I.wait(2);
  I.fillField('#txt-secondsurname', 'Caruci');
  I.wait(2);
  I.selectOption('#document_type', 'Pasaporte');
  I.wait(2);
  I.fillField('#document_number', '12345678');
  I.wait(2);
  I.fillField('#txt-nationality', 'Venezuela');
  I.wait(2);
  I.fillField('#txt-phone-number', '+99 999 99 99 99');
  pause();
  I.click('//mat-checkbox[@formcontrolname="termsAndConditions"]');
  I.wait(5);
  I.click('#btn-confirm-terms-and-conditions');
  I.wait(5);
  I.click('#btn-register-user');
  I.wait(15);
});

Scenario('Sign in and edit user profile', async ({ I }) => {
  I.amOnPage('/login');
  I.fillField('#txt-email-or-user', 'erasmotorres09@gmail.com');
  pause();
  I.click('#btn-sign-in-page');
  I.say('I am logged in');
  I.waitForElement({ css: '.button-user' }, 10);
  I.saveScreenshot('loggedIn.jpg');
  I.click({ css: '.button-user' });
  I.wait(4);
  I.click('Perfil de usuario');
  I.wait(5);
  I.click('//button[@aria-label="Genero"]');
  I.wait(5);
  I.click('//mat-select[@formcontrolname="gender"]');
  I.wait(2);
  I.click('//mat-option[@value="m"]');
  I.wait(2);
  I.click('Aceptar');
  I.wait(2);
  I.scrollPageToBottom();
  I.wait(2);
  I.click('//button[@aria-label="password"]');
  pause();
  I.click('Aceptar');
  I.wait(5);
  I.click('//button[@aria-label="phone"]');
  I.wait(2);
  I.fillField('//input[@formcontrolname="celphone_number"]', '+99 999 99 99 99');
  I.say('should be only allow numbers');
  I.wait(2);
  I.click('Aceptar');
  I.wait(5);
  I.click('//button[@aria-label="Direccion"]');
  I.wait(2);
  I.fillField('//input[@formcontrolname="address_state"]', 'Catalunya');
  I.wait(2);
  I.fillField('//input[@formcontrolname="address_city"]', 'Tarragona');
  I.wait(2);
  I.fillField('//input[@formcontrolname="address_district"]', 'Salou');
  I.wait(2);
  I.fillField('//input[@formcontrolname="address_street"]', 'Barcelona, 2');
  I.wait(2);
  I.click('Aceptar');
  I.wait(5);
  I.click('Dirección complementaria');
  I.wait(2);
  I.fillField('//input[@formcontrolname="address2"]', 'Calle de San Blas 300');
  I.wait(2);
  I.fillField('//input[@formcontrolname="correspondence_address2"]', 'Puerta 14 Piso 4');
  I.wait(2);
  I.click('Aceptar');
  I.wait(2);
  I.scrollPageToTop();
  I.wait(5);
  I.click({ css: '.button-user' });
  I.wait(8);
  I.click('Cerrar sesión');
  I.wait(10);
});
